
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container
  template:
    metadata:
      labels:
        app: multi-container
    spec:
      imagePullSecrets:
      - name: regcred
    
      containers:
        - name: frontend-container
          image: "123456789012.dkr.ecr.us-west-2.amazonaws.com/insta-frontend:latest"
        - name: backend-container
          image: "123456789012.dkr.ecr.us-west-2.amazonaws.com/insta-backend:latest"

