apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container
  template:
    metadata:
      labels:
        app: multi-container
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: frontend-container
        image: <AWS_ACCOUNT_ID>.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-frontend-image:latest
        ports:
        - containerPort: 3000
      - name: backend-container
        image: <AWS_ACCOUNT_ID>.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-backend-image:latest
        ports:
        - containerPort: 8000

