apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-backend-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http   # This should match the 'name' in your Service ports
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
